const sb = window.supabase.createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY);
const $ = id => document.getElementById(id);
function msg(text, ok=false){const e=$('authMsg'); if(!e)return; e.textContent=text; e.className='auth-msg '+(ok?'success':'error'); e.style.display='block';}
function go(url){window.location.href=url;}

async function login(e){e.preventDefault(); const email=$('email').value.trim(), password=$('password').value; const btn=$('submitBtn'); btn.disabled=true; btn.textContent='Signing in…';
 const {error}=await sb.auth.signInWithPassword({email,password}); if(error){msg(error.message);btn.disabled=false;btn.textContent='Login';return;} msg('Login successful. Redirecting…',true); setTimeout(()=>go('index.html'),500); }
async function signup(e){e.preventDefault(); const name=$('name').value.trim(), email=$('email').value.trim(), password=$('password').value, confirm=$('confirmPassword').value; if(password!==confirm){msg('Passwords do not match.');return;} const btn=$('submitBtn');btn.disabled=true;btn.textContent='Creating account…';
 const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:location.origin+location.pathname.replace('signup.html','login.html')}}); if(error){msg(error.message);btn.disabled=false;btn.textContent='Create Account';return;} if(data.session){msg('Account created successfully. Redirecting…',true);setTimeout(()=>go('index.html'),700);} else {msg('Account created. Please check your email to confirm your account, then log in.',true);btn.disabled=false;btn.textContent='Create Account';} }
async function forgot(e){e.preventDefault();const email=$('email').value.trim();const btn=$('submitBtn');btn.disabled=true;btn.textContent='Sending…';const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname.replace('forgot-password.html','reset-password.html')});if(error){msg(error.message);btn.disabled=false;btn.textContent='Send Reset Link';return;}msg('Password reset link sent. Please check your email.',true);btn.disabled=false;btn.textContent='Send Reset Link';}
async function reset(e){e.preventDefault();const p=$('password').value,c=$('confirmPassword').value;if(p!==c){msg('Passwords do not match.');return;}const btn=$('submitBtn');btn.disabled=true;btn.textContent='Updating…';const {error}=await sb.auth.updateUser({password:p});if(error){msg(error.message);btn.disabled=false;btn.textContent='Update Password';return;}msg('Password updated successfully. You can now log in.',true);setTimeout(()=>go('login.html'),900);}
