-- Work Flow Professional Recruitment Portal schema
create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade, full_name text, phone text, location text, experience text, cv_path text, role text not null default 'candidate' check(role in ('candidate','employer','admin')), company_name text, company_description text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.jobs(id uuid primary key default gen_random_uuid(), employer_id uuid references auth.users(id) on delete set null, title text not null, company text not null, location text not null, category text not null, description text, requirements text, salary_min numeric, salary_max numeric, job_type text not null default 'Full Time', experience text, status text not null default 'published' check(status in ('draft','published','closed')), created_at timestamptz default now());
create table if not exists public.applications(id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, job_id uuid references public.jobs(id) on delete set null, job_title text not null, status text not null default 'Applied' check(status in ('Applied','Under Review','Shortlisted','Selected','Rejected')), candidate_name text, phone text, cv_path text, created_at timestamptz not null default now(), updated_at timestamptz default now());
create table if not exists public.saved_jobs(user_id uuid references auth.users(id) on delete cascade, job_id uuid references public.jobs(id) on delete cascade, created_at timestamptz default now(), primary key(user_id,job_id));
create table if not exists public.notifications(id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, message text not null, is_read boolean not null default false, created_at timestamptz default now());
create or replace function public.is_role(r text) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role=r) $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','')) on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
alter table public.profiles enable row level security; alter table public.jobs enable row level security; alter table public.applications enable row level security; alter table public.saved_jobs enable row level security; alter table public.notifications enable row level security;
drop policy if exists profiles_self_select on public.profiles; create policy profiles_self_select on public.profiles for select to authenticated using(id=auth.uid() or public.is_role('admin'));
drop policy if exists profiles_self_update on public.profiles; create policy profiles_self_update on public.profiles for update to authenticated using(id=auth.uid() or public.is_role('admin')) with check(id=auth.uid() or public.is_role('admin'));
drop policy if exists profiles_self_insert on public.profiles; create policy profiles_self_insert on public.profiles for insert to authenticated with check(id=auth.uid());
drop policy if exists jobs_public_read on public.jobs; create policy jobs_public_read on public.jobs for select using(status='published' or employer_id=auth.uid() or public.is_role('admin'));
drop policy if exists jobs_employer_insert on public.jobs; create policy jobs_employer_insert on public.jobs for insert to authenticated with check(employer_id=auth.uid() and (public.is_role('employer') or public.is_role('admin')));
drop policy if exists jobs_employer_update on public.jobs; create policy jobs_employer_update on public.jobs for update to authenticated using(employer_id=auth.uid() or public.is_role('admin')) with check(employer_id=auth.uid() or public.is_role('admin'));
drop policy if exists jobs_employer_delete on public.jobs; create policy jobs_employer_delete on public.jobs for delete to authenticated using(employer_id=auth.uid() or public.is_role('admin'));
drop policy if exists apps_self_select on public.applications; create policy apps_self_select on public.applications for select to authenticated using(user_id=auth.uid() or public.is_role('admin') or exists(select 1 from public.jobs j where j.id=job_id and j.employer_id=auth.uid()));
drop policy if exists apps_self_insert on public.applications; create policy apps_self_insert on public.applications for insert to authenticated with check(user_id=auth.uid());
drop policy if exists apps_employer_update on public.applications; create policy apps_employer_update on public.applications for update to authenticated using(public.is_role('admin') or exists(select 1 from public.jobs j where j.id=job_id and j.employer_id=auth.uid())) with check(public.is_role('admin') or exists(select 1 from public.jobs j where j.id=job_id and j.employer_id=auth.uid()));
drop policy if exists saved_self on public.saved_jobs; create policy saved_self on public.saved_jobs for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists notif_self on public.notifications; create policy notif_self on public.notifications for select to authenticated using(user_id=auth.uid());
drop policy if exists notif_update on public.notifications; create policy notif_update on public.notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
insert into storage.buckets(id,name,public) values('candidate-cvs','candidate-cvs',false) on conflict(id) do nothing;
drop policy if exists cv_upload_own on storage.objects; create policy cv_upload_own on storage.objects for insert to authenticated with check(bucket_id='candidate-cvs' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists cv_read_own on storage.objects; create policy cv_read_own on storage.objects for select to authenticated using(bucket_id='candidate-cvs' and ((storage.foldername(name))[1]=auth.uid()::text or public.is_role('admin') or public.is_role('employer')));
drop policy if exists cv_update_own on storage.objects; create policy cv_update_own on storage.objects for update to authenticated using(bucket_id='candidate-cvs' and (storage.foldername(name))[1]=auth.uid()::text) with check(bucket_id='candidate-cvs' and (storage.foldername(name))[1]=auth.uid()::text);
create index if not exists jobs_filters_idx on public.jobs(location,category,job_type,status); create index if not exists apps_user_idx on public.applications(user_id,created_at desc); create index if not exists apps_job_idx on public.applications(job_id,created_at desc);
-- To make a trusted account an employer/admin, run manually as an existing admin: update public.profiles set role='employer' where id='USER_UUID';
insert into public.jobs(title,company,location,category,description,requirements,salary_min,salary_max,job_type,experience,status) select 'Multilingual Customer Support Executive','Work Flow Partner','Dubai, UAE','Customer Support','Customer service role for candidates with strong communication skills.','English plus additional languages preferred.',4000,6000,'Full Time','1-2 years','published' where not exists(select 1 from public.jobs where title='Multilingual Customer Support Executive');
insert into public.jobs(title,company,location,category,description,requirements,salary_min,salary_max,job_type,experience,status) select 'Facility Management Coordinator','Work Flow Partner','Dubai, UAE','Facilities','Coordinate facility operations and vendor activities.','Good coordination and communication skills.',5000,7000,'Full Time','2-4 years','published' where not exists(select 1 from public.jobs where title='Facility Management Coordinator');
insert into public.jobs(title,company,location,category,description,requirements,salary_min,salary_max,job_type,experience,status) select 'Sales Associate','Work Flow Partner','UAE','Sales','Customer-facing sales opportunity for motivated candidates.','Communication and sales skills preferred.',3000,4500,'Full Time','0-2 years','published' where not exists(select 1 from public.jobs where title='Sales Associate');
-- Security hardening: candidates cannot self-promote to employer/admin.
create or replace function public.protect_profile_role() returns trigger language plpgsql security definer set search_path=public as $$ begin if old.role is distinct from new.role and not public.is_role('admin') then new.role:=old.role; end if; return new; end; $$;
drop trigger if exists protect_profile_role_trigger on public.profiles; create trigger protect_profile_role_trigger before update on public.profiles for each row execute function public.protect_profile_role();
-- Only the employer/admin responsible for a job can create a status notification for its applicant.
drop policy if exists notif_employer_insert on public.notifications; create policy notif_employer_insert on public.notifications for insert to authenticated with check(public.is_role('admin') or exists(select 1 from public.applications a join public.jobs j on j.id=a.job_id where a.user_id=notifications.user_id and j.employer_id=auth.uid()));
-- Tighten CV reads: candidates can read their own CV; employers can read only CVs attached to applications for their jobs; admins can read all.
drop policy if exists cv_read_own on storage.objects; create policy cv_read_own on storage.objects for select to authenticated using(bucket_id='candidate-cvs' and ((storage.foldername(name))[1]=auth.uid()::text or public.is_role('admin') or exists(select 1 from public.applications a join public.jobs j on j.id=a.job_id where a.cv_path=name and j.employer_id=auth.uid())));
